### ISSUE TITLE
Velero backup fails when inducing pool failure.

### ISSUE THREAD

**Issue by shashank855** [openebs/e2e-tests#176] opened 2020-02-27 23:45 UTC
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:
```
devuser@mlrack1:~$ velero backup get
NAME                         STATUS                      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
newschedule-20200227233642   PartiallyFailed (1 error)   2020-02-27 23:36:42 +0000 UTC   29d       default            <none>
newschedule-20200227233442   PartiallyFailed (1 error)   2020-02-27 23:34:42 +0000 UTC   29d       default            <none>
newschedule-20200227233242   PartiallyFailed (1 error)   2020-02-27 23:32:42 +0000 UTC   29d       default            <none>
newschedule-20200227233042   PartiallyFailed (1 error)   2020-02-27 23:30:42 +0000 UTC   29d       default            <none>
newschedule-20200227232842   PartiallyFailed (1 error)   2020-02-27 23:28:42 +0000 UTC   29d       default            <none>
newschedule-20200227232642   PartiallyFailed (1 error)   2020-02-27 23:26:42 +0000 UTC   29d       default            <none>
newschedule-20200227232442   PartiallyFailed (1 error)   2020-02-27 23:24:42 +0000 UTC   29d       default            <none>
newschedule-20200227232242   PartiallyFailed (1 error)   2020-02-27 23:22:42 +0000 UTC   29d       default            <none>
newschedule-20200227232042   PartiallyFailed (1 error)   2020-02-27 23:20:42 +0000 UTC   29d       default            <none>
newschedule-20200227231842   PartiallyFailed (1 error)   2020-02-27 23:18:42 +0000 UTC   29d       default            <none>
newschedule-20200227231642   PartiallyFailed (1 error)   2020-02-27 23:16:42 +0000 UTC   29d       default            <none>
newschedule-20200227231442   PartiallyFailed (1 error)   2020-02-27 23:14:42 +0000 UTC   29d       default            <none>
newschedule-20200227231242   PartiallyFailed (1 error)   2020-02-27 23:12:42 +0000 UTC   29d       default            <none>
newschedule-20200227230853   PartiallyFailed (1 error)   2020-02-27 23:08:53 +0000 UTC   29d       default            <none>
```

While creating schedule backup on velero for cstor volume with three repicas. On bringing down the two of the pool pods all the scheduled backup is failed.

**What you expected to happen**:
Once the pool pod comes to running state the scheduled backup should completes successfully.

**How to reproduce it (as minimally and precisely as possible)**:
- Provision velero server
- Use GCP bucket for object storage.
- Create schedule
- Once the first backup is Inprogres state delete pool pods.
**Anything else we need to know?**:
- Platform: Openshift-4.2

**Comment by mynktl** [comment] 2020-04-07 15:08
@shashank855 This is expected behavior. If pool pod on which backup is running gets restarted then backup will be marked as failed.

**Comment by mynktl** [comment] 2020-04-07 15:09
@shashank855 Can you close this issue, since this is expected behavior?

**Closed as completed** 2020-04-15 13:50 UTC
