### ISSUE TITLE
target affinity check util fails for csi based cstor volumes

### ISSUE THREAD

**Issue by gprasath** [openebs/e2e-tests#199] opened 2020-03-19 03:19 UTC
**What happened**:

```TASK [Derive storage engine from PV] *******************************************
2020-03-19T03:23:44.777727 (delta: 0.100552)         elapsed: 81.712128 ******* 
ok: [127.0.0.1] => {"changed": false, "resources": [{"apiVersion": "v1", "kind": "PersistentVolume", "metadata": {"annotations": {"pv.kubernetes.io/provisioned-by": "cstor.csi.openebs.io"}, "creationTimestamp": "2020-03-19T03:22:41Z", "finalizers": ["kubernetes.io/pv-protection", "external-attacher/cstor-csi-openebs-io"], "name": "pvc-bd2c6fd2-f4f0-4d21-863b-fb108bd128dd", "resourceVersion": "173829", "selfLink": "/api/v1/persistentvolumes/pvc-bd2c6fd2-f4f0-4d21-863b-fb108bd128dd", "uid": "e077be50-ad36-48f5-8f11-c20460814ab1"}, "spec": {"accessModes": ["ReadWriteOnce"], "capacity": {"storage": "15Gi"}, "claimRef": {"apiVersion": "v1", "kind": "PersistentVolumeClaim", "name": "percona-mysql-claim", "namespace": "percona", "resourceVersion": "173772", "uid": "bd2c6fd2-f4f0-4d21-863b-fb108bd128dd"}, "csi": {"driver": "cstor.csi.openebs.io", "fsType": "ext4", "volumeAttributes": {"openebs.io/cas-type": "cstor", "storage.kubernetes.io/csiProvisionerIdentity": "1584550299705-8081-cstor.csi.openebs.io"}, "volumeHandle": "pvc-bd2c6fd2-f4f0-4d21-863b-fb108bd128dd"}, "persistentVolumeReclaimPolicy": "Delete", "storageClassName": "openebs-csi", "volumeMode": "Filesystem"}, "status": {"phase": "Bound"}}]}

TASK [debug] *******************************************************************
2020-03-19T03:23:45.562501 (delta: 0.784721)         elapsed: 82.496902 ******* 
fatal: [127.0.0.1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'openebs.io/cas-type'\n\nThe error appears to have been in '/utils/scm/openebs/target_affinity_check.yml': line 31, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- debug:\n  ^ here\n"}
```

**Comment by nsathyaseelan** [comment] 2020-07-09 04:52
duplicate of https://github.com/openebs/e2e-tests/issues/311

**Closed as completed by nsathyaseelan** 2020-07-09 04:52 UTC
