### ISSUE TITLE
Update replica access mode validation util to check with the replication factor

### ISSUE THREAD

**Issue by gprasath** [openebs/e2e-tests#336] opened 2020-05-10 23:24 UTC
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by nsathyaseelan** [comment] 2020-07-09 05:07
duplicate of https://github.com/openebs/e2e-tests/issues/390

**Closed as completed by nsathyaseelan** 2020-07-09 05:07 UTC
